name       : libsm
version    : 1.2.2
release    : 6
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.2.tar.bz2 : 0baca8c9f5d934450a70896c4ad38d06475521255ca63b717a6510fdb6e287bd
license    :
    - MIT
summary    : X Session Management Library
component  : xorg.library
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig32(uuid)
    - pkgconfig(ice)
    - pkgconfig32(ice)
    - pkgconfig(xtrans)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    This package provides the main interface to the X11 Session Management library, which allows for applications to both manage sessions, and make use of session managers to save and restore their state for later use.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
