name       : libsm
version    : 1.2.3
release    : 11
source     :
    - https://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.3.tar.bz2 : 2d264499dcb05f56438dee12a1b4b71d76736ce7ba7aa6efbf15ebb113769cbb
license    : MIT
component  : xorg.library
summary    : X Session Management Library
description: |
    This package provides the main interface to the X11 Session Management library, which allows for applications to both manage sessions, and make use of session managers to save and restore their state for later use.
emul32     : yes
builddeps  :
    - pkgconfig32(ice)
    - pkgconfig32(x11)
    - pkgconfig32(uuid)
    - pkgconfig(xtrans)
    - pkgconfig(xproto) # for better discovery
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
